pipeline {
    //environment {
    //    registry = 'kotulev/ftask'
    //    registryCredential = 'DockerHub'
    //    dockerImage = ''
    }
    agent any
    stages {
        stage('intermine build') {
            steps {
                sh 'ls -al'
                //sh 'mv dockerhub.docker-compose.yml dockerhub.docker-compose.yml-'
                sh 'ls -al'
                sh 'docker-compose -f docker-intermine-gradle-master/local.docker-compose.yml build'
                sh 'echo "build"'
            }
        }
    }
}
