pipeline {
    agent any
    stages {
        stage('intermine build') {
            steps {
                #sh 'cd  docker-intermine-gradle-master'
                sh 'ls -al'
                sh 'mv dockerhub.docker-compose.yml dockerhub.docker-compose.yml-'
                sh 'docker-compose build'
                sh 'echo "build"'
            }
        }
    }
}
